pool: my-personal-computer

variables:
  phpVersion: 7.2

steps:
- script: |
    sudo update-alternatives --set php /usr/bin/php7.2
    sudo update-alternatives --set phar /usr/bin/phar7.2
    sudo update-alternatives --set phpdbg /usr/bin/phpdbg7.2
    sudo update-alternatives --set php-cgi /usr/bin/php-cgi7.2
    sudo update-alternatives --set phar.phar /usr/bin/phar.phar7.2
    php -version
  displayName: 'Use PHP version 7.2'